### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by lijunboy008** [Countly/countly-server#607]
when i delpoy the docker countly ，there is error in the the docker logs ：
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
exception: connect failed

[dashboard] waiting for MongoDB to allocate files ...
exception: connect failed

[api] waiting for MongoDB to allocate files ...
Aug 15 01:43:11 countly0815-664d96cdb6-4s7ks syslog-ng[21]: syslog-ng starting up; version='3.5.3'
        "collections" : 0,
        "collections" : 0,
[dashboard] MongoDB started
[api] MongoDB started
2018-08-15T01:43:16.090Z: INFO  [jobs:manager]  Starting job manager
2018-08-15T01:43:16.124Z: INFO  [jobs:scanner]  Checking plugins ["mobile","web","desktop","plugins","density","locale","browser","sources","views","enterpriseinfo"
,"logger","systemlogs","errorlogs","populator","reports","crashes","push","star-rating","slipping-away-users","compare","server-stats","dbviewer","assistant","plugi
n-upload","times-of-day","compliance-hub","video-intelligence-monetization","alerts"]
2018-08-15T01:43:17.095Z: INFO  [jobs:manager]  Found 14 job types, starting monitoring: ["api:clear","api:clearTokens","api:ipcTest","api:ping","api:userMerge","re
ports:send","push:build","push:cleanup","push:clear","push:send","push:validate","server-stats:stats","assistant:generate","alerts:monitor"]
/opt/countly/node_modules/traverse/index.js:38
        if (!hasOwnProperty.call(node, key)) node[key] = {};
                            ^

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at Traverse.set (/opt/countly/node_modules/traverse/index.js:38:29)
    at read (/opt/countly/api/configextender.js:58:12)
    at module.exports (/opt/countly/api/configextender.js:63:5)
    at Object.<anonymous> (/opt/countly/api/config.js:132:45)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
/opt/countly/node_modules/traverse/index.js:38
        if (!hasOwnProperty.call(node, key)) node[key] = {};
                            ^

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at Traverse.set (/opt/countly/node_modules/traverse/index.js:38:29)
    at read (/opt/countly/api/configextender.js:58:12)
    at module.exports (/opt/countly/api/configextender.js:63:5)
    at Object.<anonymous> (/opt/countly/api/config.js:132:45)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
/opt/countly/node_modules/traverse/index.js:38
        if (!hasOwnProperty.call(node, key)) node[key] = {};
                            ^
```
and the countly 3001 port not started，but 6001 port is started
the countly web site has some 502 (Bad Gateway),I don't know what this error means.  and docker keep reporting this error

**Comment by iartem** [comment]
Could you list env variables you set for that container?

**Comment by lijunboy008** [comment]
Hi @iartem , this is the container env , by the way i use the kubernetes 1.10.1 version to deploy the countly
```
ubuntu@k8smaster-215:~$ kubectl get pod
NAME                     READY     STATUS    RESTARTS   AGE
countly-6bbf9765-g7kjm   1/1       Running   0          7h
ubuntu@k8smaster-215:~$ kubectl exec -it countly-6bbf9765-g7kjm -- bash
root@countly-6bbf9765-g7kjm:/# env
ARGO_UI_PORT_80_TCP_ADDR=10.101.12.1
HOSTNAME=countly-6bbf9765-g7kjm
TF_HUB_LB_PORT_80_TCP_PORT=80
GLUSTERFS_DYNAMIC_COUNTLY_GF_PORT_1_TCP_ADDR=10.111.195.83
GLUSTERFS_DYNAMIC_COUNTLY_GF_PORT_1_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
TERM=xterm
ARGO_UI_PORT_80_TCP_PORT=80
KUBERNETES_SERVICE_PORT=443
TF_HUB_LB_PORT_80_TCP=tcp://10.105.50.222:80
KUBERNETES_SERVICE_HOST=10.96.0.1
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
ARGO_UI_PORT_80_TCP_PROTO=tcp
TF_HUB_LB_SERVICE_PORT=80
TF_HUB_LB_SERVICE_PORT_HUB=80
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GLUSTERFS_DYNAMIC_COUNTLY_GF_SERVICE_PORT=1
PWD=/
TF_HUB_LB_PORT_80_TCP_ADDR=10.105.50.222
GLUSTERFS_DYNAMIC_COUNTLY_GF_PORT_1_TCP_PORT=1
TF_HUB_LB_PORT_80_TCP_PROTO=tcp
ARGO_UI_PORT=tcp://10.101.12.1:80
GLUSTERFS_DYNAMIC_COUNTLY_GF_PORT=tcp://10.111.195.83:1
GLUSTERFS_DYNAMIC_COUNTLY_GF_PORT_1_TCP=tcp://10.111.195.83:1
ARGO_UI_SERVICE_PORT=80
INSIDE_DOCKER=1
TF_HUB_LB_SERVICE_HOST=10.105.50.222
SHLVL=1
HOME=/root
ARGO_UI_SERVICE_HOST=10.101.12.1
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
GLUSTERFS_DYNAMIC_COUNTLY_GF_SERVICE_HOST=10.111.195.83
ARGO_UI_PORT_80_TCP=tcp://10.101.12.1:80
LESSOPEN=| /usr/bin/lesspipe %s
TF_HUB_LB_PORT=tcp://10.105.50.222:80
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
```

this is my kubernetes yaml, it's very simple
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: countly-server
  namespace: xlab-countly
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: countly
    spec:
      containers:
      - name: countly
        image: countly/countly-server
        ports:
          - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: k8snodebasic-214
```

**Comment by absrivastava** [comment]
@lijunboy008 I am also trying to setup countly on kubernetes, for me it works fine if I only creates deployment, but as soon as I try to create deployment and service it fails. ( Details here #612 )
 I also came across the error you mentioned, when I was trying to add multiple ports to service, are you also doing something similar

Service Spec which I was trying with multiple ports:
```
kind: Service
apiVersion: v1
metadata:
  labels:
    app: countly
  name: countly
  namespace: default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  selector:
    app: countly
```

Deployment Spec:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: countly
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: countly
    spec:
      containers:
      - name: countly
        image: countly/countly-server
        ports:
        - containerPort: 80

```

**Comment by lijunboy008** [comment]
@absrivastava  when i create deployment and service together, it fails.  yes，i'am also the same error，but my service.yaml use the one port .this is my  service.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: countly-server
  namespace: xlab-countly
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
spec:
  #externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: countly
    nodePort: 31800
    port: 80
    targetPort: 80
  selector:
    app: countly
```

when  i  first apply the  countly yaml  and then apply the service.yaml, it works well 
And i  kubectl delete -f  deployment_countly.yaml  , and then  kubectl apply -f  deployment_countly.yaml  to recreate the countly, There will be an error like yours 
if  i delete the service.yaml，and  recreate the countly yaml ，it works well 

so may be ，it must apply the  countly yaml first and then  apply the service.yaml，but if i restart k8s ，the error will happen。

maybe set up the boot sequence between countly yaml  and service.yaml ，I don't know why it is like this.
