### ISSUE TITLE
Running Countly Server on Kubernetes - getting error 'Cannot set property 'tcp' of undefined'

### ISSUE THREAD

**Issue by absrivastava** [Countly/countly-server#612]
Trying to run Countly Server on Kubernetes.
It runs fine with Deployment alone but if I create Service and Deployment together, it starts throwing error.

Note: If I create deployment alone, it works. But I need to create service as well, to allow connecting to admin panel and API from outside cluster.

K8s Spec:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: countly
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: countly
    spec:
      containers:
      - name: countly
        image: countly/countly-server
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: countly
  name: countly
  namespace: default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: countly
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-countly
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: countly.local
    http:
      paths:
      - path: /
        backend:
          serviceName: countly
          servicePort: 80
```

**Error:**
```
[api] MongoDB started
/opt/countly/node_modules/traverse/index.js:41
    node[ps[i]] = value;
                ^
 TypeError: Cannot set property 'tcp' of undefined
    at Traverse.set (/opt/countly/node_modules/traverse/index.js:41:17)
    at read (/opt/countly/api/configextender.js:58:12)
    at module.exports (/opt/countly/api/configextender.js:63:5)
    at Object.&lt;anonymous&gt; (/opt/countly/api/config.js:129:45)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
	"collections" : 0,
```

**Comment by absrivastava** [comment]
Closing this one. Found the issue behind this, so when Service when get maps to containers, few variables are defined and passed to container. For Example, if your service name is countly-server then following variables will be passed: 
```
COUNTLY_SERVER_SERVICE_HOST=<the host on which service is running>
COUNTLY_SERVER_SERVICE_PORT=<the port on which service is running>

```
so when configextender.js parses env, it gets env variable starting with COUNTLY_ and it starts parsing, hence the error.

Note: even if you use hyphens, it will convert it to underscore and pass to container.

Here is the Spec:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: countly
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: countly
    spec:
      containers:
      - name: countly
        image: countly/countly-server:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: countly
  name: countlyservice
  namespace: default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: countly
---
```
